/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[FirstName]
      ,[LastName]
      ,[Email]
      ,[LoginId]
      ,[Password]
      ,[ConfirmPassword]
      ,[ContactNumber]
  FROM [TweetDB].[dbo].[TblLogin]